In [2]:
import pandas as pd

In [3]:
acc_vs_seq=pd.read_csv('non_GH_of_interest.csv') #read the csv file containing the length of each sequence as well, obtained from Get_EC_GH.ipynb
#acc_vs_seq.rename( columns={'Unnamed: 0':'ID'}, inplace=True ) #rename the unnamed column as ID
acc_vs_seq

,ID,EC number,Taxonomy,GH family,Sequence,Length
0,CUX77898.1,3.2.1.-,Archaea,GH0,MGLKRLLVLVVAVVVLSSGINFSWALGNRPSEGTGVAGKLSFKATF...,805
1,BAU88504.1,3.2.1.-,Archaea,GH0,MGLKRLLVLVVAVVVLSSGINFSWALGNRPSEGTGVAGKLSFKATF...,805
2,AAG06182.1,3.2.1.-,Bacteria,GH0,MNTYFDIPHRLVGKALYESYYDHFGQMDILSDGSLYLIYRRATEHV...,438
3,AAF60322.2,3.2.1.-,Bacteria,GH0,MNTYFDIPHRLVGKALYESYYDHFGQMDILSDGSLYLIYRRATEHV...,438
4,AAG06872.1,3.2.1.-,Bacteria,GH0,MTATSDLIESLISYSWDDWQVTRQEARRVIAAIRNDNVPDATIAAL...,408
...,...,...,...,...,...,...
5891,AQR80106.1,3.2.1.92,Bacteria,GH171,MRKTIFAFLTGLMMFGTITAASASPDSKNQTAKKPKVQTGIDTLLP...,414
5892,AQR84319.1,3.2.1.92,Bacteria,GH171,MRKTIFAFLTGLMMFGTITAASASPDSKNQTAKKPKVQTGIDTLLP...,414
5893,QJF42043.1,3.2.1.92,Bacteria,GH171,MRKTIFAFLTGLMMFGTITAASASPDSKNQTAKKPKVQTGIDTLLP...,414
5894,BAQ28034.1,4.2.1.179 3.2.1.- 3.2.1.-,Bacteria,GH172,MSEITGLFKDLTKVKHARNGRLASWDQRGKNQDYWEIPAGESITLG...,452
5895,UMW87594.1,3.2.1.23,Bacteria,GH173,MKCNKLFVGAAALLLTLGSCSHSNGEWLTLIPGEPNPHAIECIGAE...,502

In [4]:
acc_vs_seq.describe() #statistical description of the dataset

            Length
count  5896.000000
mean    522.023915
std     203.940952
min      64.000000
25%     368.000000
50%     514.000000
75%     669.000000
max     999.000000

In [5]:
acc_vs_seq=acc_vs_seq[acc_vs_seq.Length <1000] #removing sequences more than 1000 and less than 60 amino acids long
acc_vs_seq=acc_vs_seq[acc_vs_seq.Length >60]
acc_vs_seq.reset_index(inplace = True, drop = True) #resetting the index, as after dropping there are missing index values
acc_vs_seq

,ID,EC number,Taxonomy,GH family,Sequence,Length
0,CUX77898.1,3.2.1.-,Archaea,GH0,MGLKRLLVLVVAVVVLSSGINFSWALGNRPSEGTGVAGKLSFKATF...,805
1,BAU88504.1,3.2.1.-,Archaea,GH0,MGLKRLLVLVVAVVVLSSGINFSWALGNRPSEGTGVAGKLSFKATF...,805
2,AAG06182.1,3.2.1.-,Bacteria,GH0,MNTYFDIPHRLVGKALYESYYDHFGQMDILSDGSLYLIYRRATEHV...,438
3,AAF60322.2,3.2.1.-,Bacteria,GH0,MNTYFDIPHRLVGKALYESYYDHFGQMDILSDGSLYLIYRRATEHV...,438
4,AAG06872.1,3.2.1.-,Bacteria,GH0,MTATSDLIESLISYSWDDWQVTRQEARRVIAAIRNDNVPDATIAAL...,408
...,...,...,...,...,...,...
5891,AQR80106.1,3.2.1.92,Bacteria,GH171,MRKTIFAFLTGLMMFGTITAASASPDSKNQTAKKPKVQTGIDTLLP...,414
5892,AQR84319.1,3.2.1.92,Bacteria,GH171,MRKTIFAFLTGLMMFGTITAASASPDSKNQTAKKPKVQTGIDTLLP...,414
5893,QJF42043.1,3.2.1.92,Bacteria,GH171,MRKTIFAFLTGLMMFGTITAASASPDSKNQTAKKPKVQTGIDTLLP...,414
5894,BAQ28034.1,4.2.1.179 3.2.1.- 3.2.1.-,Bacteria,GH172,MSEITGLFKDLTKVKHARNGRLASWDQRGKNQDYWEIPAGESITLG...,452
5895,UMW87594.1,3.2.1.23,Bacteria,GH173,MKCNKLFVGAAALLLTLGSCSHSNGEWLTLIPGEPNPHAIECIGAE...,502

In [6]:
#saving the sequences to multifasta after length trimmed
xx=(acc_vs_seq.ID.count())
with open('non_GH_of_interest.fasta','w',encoding='utf-8') as otp:
    for i in range(xx):
        acc_id=acc_vs_seq.iloc[i,0]+'&'+acc_vs_seq.iloc[i,1]+'&'+acc_vs_seq.iloc[i,3]
        seq=acc_vs_seq.iloc[i,4]
        otp.write('>'+acc_id+'\n'+seq+'\n')
print('multifasta file with no length outliers is successfully saved')

multifasta file with no length outliers is successfully saved